import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./sass/main.scss";
import { Header } from "../app/components/layout/Header";
import { getGlobalSettings } from "./data/loaders";
import { Footer } from "./components/layout/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function loader() {
  const { data } = await getGlobalSettings();
  if (!data) {
    throw new Error("Global settings not found");
  }
  return { header: data?.header, footer: data?.footer };
}

export default async function RootLayout({ children }) {
  const { header, footer } = await loader();
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Header data={header} />
        {children}
        <Footer data={footer} />
      </body>
    </html>
  );
}
